package org.example.meetingplanner.event;

public enum Event {
    MEETING_SELECTED,
    MEETING_DESELECTED,
    MEETING_CREATED,
    MEETING_CREATED_FAILED,
    MEETING_UPDATED,
    MEETING_UPDATED_FAILED,
    SEARCH_STARTED,
    MEETING_NOTE_CREATED
}
